### ISSUE TITLE
Error: No provider for ComponentLoaderFactory

### ISSUE THREAD

**Issue by ahvjohnson** [webcat12345/ngx-intl-tel-input#1]
I see this error running the demo.

**Comment by webcat12345** [comment]
How did you ran the demo?

**Comment by ahvjohnson** [comment]
cloned the project, 'npm install ngx-intl-tel-input --save' on the demo directory, then ng serve.

**Comment by webcat12345** [comment]
I created this lib yesterday and I am currently working on this.
Demo project is not completed for publish, so I didn't added demo page link on Readme.
I will update demo soon.

**Comment by ahvjohnson** [comment]
ok, thanks. Will wait on that then.

**Comment by webcat12345** [comment]
@ahvjohnson 
https://github.com/webcat12345/ngx-intl-tel-input/tree/issue-1-no-provider-for-component-loader-factory
This branch has updated demo and ReadMe.

**Comment by ahvjohnson** [comment]
works great, thanks

**Comment by thebarada** [comment]
still reproduce

**Comment by salih0313** [comment]
https://github.com/webcat12345/ngx-intl-tel-input/tree/issue-1-no-provider-for-component-loader-factory

Page not found. Still same error for me.

**Comment by makas2** [comment]
ngx-bootsrap 2.0.0
ngx-intl-tel-input 
problem still reproduced
Does anybody fixed that?

**Comment by seaBubble** [comment]
Same problem here

**Comment by yogesh-sadhokar** [comment]
Same issue for me also

**Comment by yogesh-sadhokar** [comment]
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
index.js:1375 CountryCode: "XK" Error: Invalid country calling code
core.js:1427 ERROR Error: Uncaught (in promise): Error: StaticInjectorError[ComponentLoaderFactory]: 
  StaticInjectorError[ComponentLoaderFactory]: 
    NullInjectorError: No provider for ComponentLoaderFactory!
Error: StaticInjectorError[ComponentLoaderFactory]: 
  StaticInjectorError[ComponentLoaderFactory]: 
    NullInjectorError: No provider for ComponentLoaderFactory!
    at _NullInjector.get (core.js:993)
    at resolveToken (core.js:1281)
    at tryResolveToken (core.js:1223)
    at StaticInjector.get (core.js:1094)
    at resolveToken (core.js:1281)
    at tryResolveToken (core.js:1223)
    at StaticInjector.get (core.js:1094)
    at resolveNgModuleDep (core.js:10878)
    at NgModuleRef_.get (core.js:12110)
    at resolveDep (core.js:12608)
    at _NullInjector.get (core.js:993)
    at resolveToken (core.js:1281)
    at tryResolveToken (core.js:1223)
    at StaticInjector.get (core.js:1094)
    at resolveToken (core.js:1281)
    at tryResolveToken (core.js:1223)
    at StaticInjector.get (core.js:1094)
    at resolveNgModuleDep (core.js:10878)
    at NgModuleRef_.get (core.js:12110)
    at resolveDep (core.js:12608)
    at resolvePromise (zone.js:824)
    at resolvePromise (zone.js:795)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at ZoneTask.invokeTask [as invoke] (zone.js:503)
    at invokeTask (zone.js:1540)
defaultErrorLogger @ core.js:1427
ErrorHandler.handleError @ core.js:1488
next @ core.js:5498
schedulerFn @ core.js:4339
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4319
(anonymous) @ core.js:4775
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
NgZone.runOutsideAngular @ core.js:4701
onHandleError @ core.js:4775
ZoneDelegate.handleError @ zone.js:396
Zone.runGuarded @ zone.js:158
_loop_1 @ zone.js:702
api.microtaskDrainDone @ zone.js:711
drainMicroTaskQueue @ zone.js:610
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566

**Comment by yogesh-sadhokar** [comment]
if anyone found the solution, please share

**Comment by harri1233434** [comment]
<div class="row container">
        <div>
            <button class="btn btn-grey btn-sm " type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Select &nbsp;&nbsp; <i class="fa fa-caret-down align-right" aria-hidden="true"></i>
            </button>
            <div class="dropdown-menu">
                 <a class="dropdown-item" href="#">Action</a>
                 <a class="dropdown-item" href="#">Another action</a>
                 <a class="dropdown-item" href="#">Something else here</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Separated link</a>
            </div>                         						
       </div>        
       <button  type="button" data-toggle="dropdown" class="btn btn-primary dropdown-toggle waves-light" >
          Dropdown
      </button>
      <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
          <div class="divider dropdown-divider"></div>
          <a class="dropdown-item" href="#">Separated link</a>
      </div>
    </div>
This drop down works fine.Use it to your project by making some changes

**Comment by harri1233434** [comment]
`<div class="row container">
        <div>
            <button class="btn btn-grey btn-sm " type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Select &nbsp;&nbsp; <i class="fa fa-caret-down align-right" aria-hidden="true"></i>
            </button>
            <div class="dropdown-menu">
                 <a class="dropdown-item" href="#">Action</a>
                 <a class="dropdown-item" href="#">Another action</a>
                 <a class="dropdown-item" href="#">Something else here</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Separated link</a>
            </div>                         						
       </div>        
       <button  type="button" data-toggle="dropdown" class="btn btn-primary dropdown-toggle waves-light" >
          Dropdown
      </button>
      <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
          <div class="divider dropdown-divider"></div>
          <a class="dropdown-item" href="#">Separated link</a>
      </div>
    </div>`

**Comment by harri1233434** [comment]
The above toggles a dropdown without any issues

**Comment by harri1233434** [comment]
`<div class="row container">
        <div>
            <button class="btn btn-grey btn-sm " type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Select &nbsp;&nbsp; <i class="fa fa-caret-down align-right" aria-hidden="true"></i>
            </button>
            <div class="dropdown-menu">
                 <a class="dropdown-item" href="#">Action</a>
                 <a class="dropdown-item" href="#">Another action</a>
                 <a class="dropdown-item" href="#">Something else here</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Separated link</a>
            </div>                         						
       </div>        
       <button  type="button" data-toggle="dropdown" class="btn btn-primary dropdown-toggle waves-light" >
          Dropdown
      </button>
      <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
          <div class="divider dropdown-divider"></div>
          <a class="dropdown-item" href="#">Separated link</a>
      </div>
    </div>`

**Comment by yogesh-sadhokar** [comment]
I will check

**Comment by bhawesh96** [comment]
Can someone please share the solution! Even I'm getting the same error.

**Comment by Badmonky** [comment]
Is anyone still actively working on this? Last updates on any issues where forever ago...

**Comment by lucasa** [comment]
Any fix?

**Comment by ojcgv21** [comment]
The solution is here https://github.com/webcat12345/ngx-intl-tel-input/issues/125#issuecomment-377675844
