### ISSUE TITLE
Handle security vulnerability of the repository

### ISSUE THREAD

**Issue by webcat12345** [webcat12345/ngx-intl-tel-input#143]

**Comment by pasevin** [comment]
Can you guide me what is this vulnerability? Where do you see it?

**Comment by webcat12345** [comment]
![image](https://user-images.githubusercontent.com/19761422/52187952-06683f00-27e5-11e9-876b-94afd2902781.png)
This is the screenshot. and detail goes here.

![image](https://user-images.githubusercontent.com/19761422/52188000-2bf54880-27e5-11e9-88b3-521285830c47.png)

This is not critical yet. Just keep this in mind.
