### ISSUE TITLE
Country Dropdown not working

### ISSUE THREAD

**Issue by idris-rampurawala** [webcat12345/ngx-intl-tel-input#153]
I have integrated as per the documentation. The dropdown for country does not work.

**Comment by Dviejopomata** [comment]
What error does it throw?

**Comment by idris-rampurawala** [comment]
There's no error coming up. When clicked on country flag, the dropdown just don't work. It does not pop up the list of countries.

**Comment by pasevin** [comment]
Can you share a StackBlitz link with reproduction? And check out our demo page with a working example from ReadMe.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pasevin** [comment]
This is most likely JS issue on your side @idris-rampurawala . Closing this, unless more info with reproducible example comes up.

**Comment by vidhema** [comment]
same issue happen .. I have implement this in angular 7 project and working fine .. but in ionic dropdown of country not shown .. eveything else is working fine
