### ISSUE TITLE
Canada number is resolving to us number now. Countries dropdown should be changed on the basis of area codes if same dial code given. 

### ISSUE THREAD

**Issue by imkiran** [webcat12345/ngx-intl-tel-input#157]
This is ontario canada number `+1-613-555-0191` but  the flag is still `US`. I have set 'enableAutoCountrySelect' to `true`. Can you please check it. I will reopen the issue.
<img width="277" alt="screen shot 2019-02-12 at 12 20 30 pm" src="https://user-images.githubusercontent.com/32508998/52617126-cda12780-2ec0-11e9-8cf1-160a47dd1f52.png">
<img width="274" alt="screen shot 2019-02-12 at 12 20 38 pm" src="https://user-images.githubusercontent.com/32508998/52617128-cda12780-2ec0-11e9-9350-03db0efcedbb.png">

_Originally posted by @imkiran in https://github.com/webcat12345/ngx-intl-tel-input/issues/154#issuecomment-462638821_

**Comment by pasevin** [comment]
Hey, indeed, I made a mistake. This is what you get when working late. Check out the new update.
