### ISSUE TITLE
When i have a indian number filled by default. The flag is still `US` once i click on the input it shows the `indian` flag. 

### ISSUE THREAD

**Issue by imkiran** [webcat12345/ngx-intl-tel-input#159]

**Comment by pasevin** [comment]
How do you fill it? It probably needs to trigger touch event or smth.

**Comment by somq** [comment]
I'm having exactly the same issue by setting input value in a reactive using:
```ts
this.formget('phoneNumber').setValue(this.phoneNumber)
```

However a click on the input AND a click anywhere outside of the input changes the flag.
Does [ngOnChanges](https://github.com/webcat12345/ngx-intl-tel-input/blob/master/projects/ngx-intl-tel-input/src/lib/ngx-intl-tel-input.component.ts#L97) triggers properly when a FormControl input value is set using setValue()?

**Comment by zaizac** [comment]
This one works for me.

![image](https://user-images.githubusercontent.com/9007583/62173188-b61f0380-b367-11e9-8aa8-e2369d43ae15.png)

**Comment by somq** [comment]
Ok, in fact it's not related to this lib but to ng2-smarttable and I already had found a solution for another component.

For ref: https://github.com/akveo/ng2-smart-table/issues/740
