### ISSUE TITLE
Country Dropdown is not shown

### ISSUE THREAD

**Issue by AfaaqSuhail** [webcat12345/ngx-intl-tel-input#161]
![screenshot from 2019-02-13 19-28-05](https://user-images.githubusercontent.com/40558711/52718586-a2543080-2fc5-11e9-868b-32af82f783f6.png)
I have installed all the modules which you have told. I got the input field on my screen but not the Country Dropdown , Idk whats the problem , because it doesnt show any error in console.

Plus i debug this, and found that BsDropDownModule is not in 'ngx-bootstrap/dropdown' but 'ngx-bootdtrap', but it did not work too.

Kindly, tell me about this asap.
Thanks

**Comment by pasevin** [comment]
I would suggest fixing your 'ExpressionChangedafterithasbeencheckederror' error first, which is not related to this library. And then try playing with our [demo](https://stackblitz.com/edit/ngx-intl-tel-input-demo) set up. It will help you understand the differences between your set up and the working one in the demo.

I just tried playing with it, adding ```BsDropdownModule.forRoot()``` and it works with no issues.

If you still have issues, you should try replicating it in your own StackBlitz setup and sharing it here.

But my guess is that it's not the library issue, but your own integration.

**Comment by AfaaqSuhail** [comment]
that 'ExpressionChangedafterithasbeencheckederror' is about Reactive form. I have fixed that.

**Comment by pasevin** [comment]
No StackBlitz example shared, so closing it.
