### ISSUE TITLE
Integration with Angular Material

### ISSUE THREAD

**Issue by pritamgb** [webcat12345/ngx-intl-tel-input#164]
Is there any way that I can use this with angular material?
Every time I try to put inside a <mat-form-field> its says mat-form-field must contain a MatFormFieldControl. Event after I mention matInput inside input.

**Comment by pasevin** [comment]
Not sure, haven't tried it with Angular Material. If you could share a working Stackblitz example, we could check what can be done if at all.

**Comment by KingKush** [comment]
I'd like to also use this with angular material but I see bootstrap listed as a dependency. Is bootstrap absolutely necessary for this package to work?

**Comment by danieldanielecki** [comment]
It's kind of problematic to integrate it to into Angular Material, as this package depends on Bootstrap. Tried to implement it, but Bootstrap overwrote some of the Angular Material's CSS styles in a bad way. Please check [this answer](https://stackoverflow.com/a/29326397) what happens when you integrate Bootstrap with Angular Material. By the way, such kind of dependency without relying on a Bootstrap would be really desired.

**Comment by Hasan-git** [comment]
@pasevin any solutions ?

**Comment by danieldanielecki** [comment]
@Hasan-git I fixed this using [ng2-tel-input](https://github.com/gauravsoni119/ng2-tel-input), code snippet below:
```
<mat-form-field appearance="outline">
  <input
    matInput
    ng2TelInput
    formControlName="formControlPhone"
    placeholder="Your phone number"
/>
<mat-icon matSuffix>phone</mat-icon>
<mat-hint>Your phone number with country prefix.</mat-hint>
<mat-error *ngIf="!contactForm.get('formControlPhone')!.valid"
>This is an <strong>invalid</strong> phone number.
</mat-error>
```

**Note:** I assume you know how to make [reactive forms](https://angular.io/guide/reactive-forms) (thus the **formControlName**).

Effect:
![Capture](https://user-images.githubusercontent.com/12736263/59443037-99e8f680-8dfb-11e9-999f-cd03392a7bbb.PNG)

**Comment by Hasan-git** [comment]
Thanks @danieldanielecki, it requires bootstrap ?

**Comment by danieldanielecki** [comment]
@Hasan-git as you can see from the [installation ](https://github.com/gauravsoni119/ng2-tel-input#installation) **nope**! :)
Don't hesitate to hit me up if something wouldn't work, will be super glad to help!

**Comment by pasevin** [comment]
For Angular Material @danieldanielecki solution is a way to go for now.

**Comment by Gsuz** [comment]
I'm not getting <mat-error> to show are you using a custom form validator?
