### ISSUE TITLE
Country event

### ISSUE THREAD

**Issue by KThen** [webcat12345/ngx-intl-tel-input#165]
Hi, I was wondering if there will be any support for country selected/changed event? I know that intl-tel-input has that feature under the hood, can it be exposed? That will be very helpful. Thanks.

**Comment by pasevin** [comment]
That sounds like a useful feature. Unfortunately, as it's not necessary for my current project, I can't dedicate my time for this. Maybe someone else could do a pull request. Otherwise, I will look into it at some point along the way.

**Comment by ShubhJaiswal** [comment]
if there is anyway to handle drodown key event , so we can get the selected countrydata.

**Comment by christianopaets** [comment]
I have created a pull request for that issue https://github.com/webcat12345/ngx-intl-tel-input/pull/229.

**Comment by pasevin** [comment]
Thanks to @christianopaets PR merged.
