### ISSUE TITLE
maxLength support?

### ISSUE THREAD

**Issue by turbolego** [webcat12345/ngx-intl-tel-input#173]
I tried to add **"maxLength=16"** inside **<ngx-intl-tel-input** but it does not work.

Any plans to implement maxLength support?

The maximum length of a phone number is _usually_ 15 digits according to the E.164 recommendation by the ITU-T: [https://en.wikipedia.org/wiki/E.164](https://en.wikipedia.org/wiki/E.164)

Some services also use up to 16 digits for "two-way conversations" over SMS:

[https://www.clickatell.com/products/sms/long-numbers/](https://www.clickatell.com/products/sms/long-numbers/)

[https://www.tobeprecisesms.com/our-solutions/long-number/](https://www.tobeprecisesms.com/our-solutions/long-number/)

However, some virtual numbers might be longer. For example Nrenum is an alternative enum-tree for research networks. they support more than 15 digits: 
[https://nrenum.net/policy/](https://nrenum.net/policy/)

> A Virtual number has either a non-valid E.164 number structure (e.g., longer than 15 digits) or has a valid structure but is not assigned to any national authorities or operators. The number Validation Entity is responsible for checking the numbers to be registered to NRENum.net.

>Virtual Numbers (e.g., short numbers or GDS) MAY be registered (under special conditions as agreed by the NRENum.net community).

There should be a maxLength variable (or whatever) somewhere in ngx-intl-tel-input imo. 😄 
And i would suggest to use **15** as the default config, since that's the ITU-T recommendation.
Some people might want to limit the length to under 15 digits too. 😶

**Comment by turbolego** [comment]
intl-tel-input has support for maxLength! 😄 

[https://github.com/jackocnr/intl-tel-input/pull/81](https://github.com/jackocnr/intl-tel-input/pull/81)

Possible to merge in from intl-tel-input to ngx-intl-tel-input? 😶

**Comment by pasevin** [comment]
Hey Update to 2.2.1
