### ISSUE TITLE
Search is not working within dropdown

### ISSUE THREAD

**Issue by jagdishpatil** [webcat12345/ngx-intl-tel-input#180]
I am trying to search the country from the keyboard inputs after selecting dropdown. It is not working. Is there are any extra code I have to write? Or this feature is not included in this package.

**Comment by pasevin** [comment]
Hi, this is not how this input works. Country is selected automatically based on the phone number entered. Check the demo page from Readme page. Good luck!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jagdishpatil** [comment]
@pasevin we want to search the country based on the key pressed by user (Eg, If 'i' is pressed on opened dropdown, first country starting with 'i' should get selected)  because any which way we are not allowing our users to input ISD code.

**Comment by davideloper** [comment]
This should really be the feature request here.

**Comment by pasevin** [comment]
This pull request (in progress) is solving this issue in a bit different way, but I think it's a better way than what you're proposing. https://github.com/webcat12345/ngx-intl-tel-input/pull/181

**Comment by pasevin** [comment]
Update to 2.2.1
