### ISSUE TITLE
Custom Placeholder [International/National]

### ISSUE THREAD

**Issue by makokhavictor** [webcat12345/ngx-intl-tel-input#182]
I want to set the placeholder to pick National/Local Format instead of international format that has the country code. e.g `(201) 555-0123` instead of `+1 201-555-0123` for US

**Comment by imadilkhalil** [comment]
I may have figured this one out already. I will send a PR in couple of days.

**Comment by dodomui** [comment]
Hi, intl-tel-input actually support placeholderNumberType, which to configure it for mobile and landline, does it apply to ngx-intl-tel-input as well?

```
placeholderNumberType
Type: String Default: "MOBILE"
Specify one of the keys from the global enum intlTelInputUtils.numberType e.g. "FIXED_LINE" to set the number type to use for the placeholder.
```

**Comment by ehsanagh** [comment]
any update on this?
or we need to ship to other modules?

**Comment by khoadnguyen** [comment]
Also looking for this enhancement if its available. Have a one off use case of this. Thanks!

**Comment by jaredol** [comment]
Same here, also would like this feature.
BTW - can anyone tell me if its possible for the max-length number to be the same as the placeholder length (for that country). Seems strange that it only would accept a hard-coded number

**Comment by kkagill** [comment]
Original package seems to have `nationalMode`
```
var iti = window.intlTelInput(input, {
  nationalMode: true,
  utilsScript: "../../build/js/utils.js?1603274336113" // just for formatting/placeholders etc
});
```
![image](https://user-images.githubusercontent.com/7738916/99935675-15034b80-2d16-11eb-91c7-58a576305fd9.png)

This enhancement would be very much appreciated.
