### ISSUE TITLE
flag images are not showing

### ISSUE THREAD

**Issue by shashivnaad** [webcat12345/ngx-intl-tel-input#193]

**Comment by pasevin** [comment]
Can you give some more context? The only place right now where flags are not showing is in the Demo app on Stackblitz. But it's a known non-issue.

**Comment by shashivnaad** [comment]
ok sorry  thank u

**Comment by eso32** [comment]
Hey,

just tried installing your lib but flags are not showing. I followed all steps as in the instructions any idea why?

Here's SC:
<img width="491" alt="Screenshot 2019-08-23 at 10 40 10" src="https://user-images.githubusercontent.com/24564295/63579327-ab384700-c592-11e9-9c98-8d6e3cf29a8f.png">

**Comment by miguelleitevieira** [comment]
I follow the same process that @eso32 anf get the same result.
Any fix for that?
