### ISSUE TITLE
preferredCountries is not working dynamically

### ISSUE THREAD

**Issue by ravindra495** [webcat12345/ngx-intl-tel-input#194]
I'm not able to access preferred countries dynamically when I changed my preferred country from other component (I am able to insert in to preferredCountries (array of strings) but it is not reflecting in flag section).
Can any one help me out in this? Thanks in advance

**Comment by pasevin** [comment]
I think this PR will solve this issue for you (still in progress): https://github.com/webcat12345/ngx-intl-tel-input/pull/181

**Comment by pasevin** [comment]
Update to 2.2.1
