### ISSUE TITLE
imposible to reset form after validation , why?

### ISSUE THREAD

**Issue by rinaharry** [webcat12345/ngx-intl-tel-input#195]

**Comment by pasevin** [comment]
Not sure what you mean. More information would be helpful.

**Comment by rinahsoku** [comment]
i reset my form after validation with  " this.form.reset() ", but the only ngx-intl-tel-input  is not reset

**Comment by zaizac** [comment]
I encounter the same thing. If you setValue on the form, assigning null or empty string does not work. You have to assign a space or any value.

**Not working:**
this.forms.controls.phoneNumber.setValue(null);
this.forms.controls.phoneNumber.setValue('');

**Working:**
this.forms.controls.phoneNumber.setValue(' ');
this.forms.controls.phoneNumber.setValue(1);

But this is not the ideal behavior.

**Comment by zaizac** [comment]
Temporary solution that works for me:
1. Accessing the child component.
@ViewChild(NgxIntlTelInputComponent) ngxIntl: NgxIntlTelInputComponent;

2. Assigning 'null' to phoneNumber when resetting the form
this.ngxIntl.phoneNumber = null;

**Comment by pasevin** [comment]
If anyone has an idea why this is happening and if it's a bug, do not hesitate to chime in ;) or submit a PR.

**Comment by pasevin** [comment]
Whops wrong button :]]]

**Comment by zaizac** [comment]
> Temporary solution that works for me:
> 
> 1. Accessing the child component.
>    @ViewChild(NgxIntlTelInputComponent) ngxIntl: NgxIntlTelInputComponent;
> 2. Assigning 'null' to phoneNumber when resetting the form
>    this.ngxIntl.phoneNumber = null;

It seems this solution is no longer working after the new build v2.2.1

**Comment by Jargon64** [comment]
This is still an issue. Looks like `setTimeout(...)` triggers after the form `reset(...)` call marks the control as pristine and dirties it again.
```js
writeValue(obj: any): void {
  if (obj == null) {
    this.ngOnInit();
  }
  this.phoneNumber = obj;
  setTimeout(() => {
    this.onPhoneNumberChange();
  }, 1);
}
```
What's the reason for `this.onPhoneNumberChange()` being wrapped in a `setTimeout(...)`?

**Comment by pasevin** [comment]
@Jargon64 I'm not seeing it, check https://stackblitz.com/edit/ngx-intl-tel-input-demo
'Reset' button works fine. Can you show a similar example when it doesn't work?

**Comment by dewert** [comment]
I'm trying to disable a submit button when a form is pristine, but the inclusion of the phone number field makes it so the form is immediately dirty. Looks to be the same issue, but let me know if I should file a new one.

In any case, here's a repro of the problem: https://ngx-intl-tel-input-demo-twiwmz.stackblitz.io
The submit button is set to disabled on `form.pristine`. Removing the phone number field from the form restores the correct behaviour.

Thanks for looking into this!

@zaizac Thanks for the hint about a workaround - I'll give that a try
