### ISSUE TITLE
Not able to see the dropdown for countries

### ISSUE THREAD

**Issue by rcogal** [webcat12345/ngx-intl-tel-input#197]
Followed the detailed steps but what I see is just a normal text field with a number placeholder for a specific country.

NOTE: there's no icon for dropdown countries on the left side of the text field

**Comment by johangel** [comment]
Same problem, tho its a malfunction from the css, the databinding is working as intended, hope they can fix it soon.

**Comment by johangel** [comment]
I just figured its just a problem with the last version release, replace this in your package.json, that should do the trick, those are the same versions they used for the example.

"bootstrap": "^4.2.1",
"intl-tel-input": "^14.0.7",
"ngx-bootstrap": "^3.2.0",
"ngx-intl-tel-input": "^2.0.7",

**Comment by vdurante** [comment]
@johangel only `"intl-tel-input": "^14.0.7",` is needed. The rest doesn't need a downgrade

**Comment by johangel** [comment]
Didn't bother to try them in one by one, thanks for the aclaration.

**Comment by rcogal** [comment]
Thanks, Guys. I appreciate it.

**Comment by pasevin** [comment]
@johangel is correct, this lib doesn't work with latest ```intl-tel-input```. For me it's not a deal breaker. But if anyone can look into it, that would be awesome ;) Otherwise I will work on it only when my own implementation needs it.

**Comment by romanzks** [comment]
> @johangel only `"intl-tel-input": "^14.0.7",` is needed. The rest doesn't need a downgrade

"bootstrap": "^4.2.1" also is needed

**Comment by graphee-gabriel** [comment]
Could be nice to precise in the readme.md 

> **Install Dependencies**
> `$ npm install intl-tel-input@14.0.7 --save`

I lost a good hour looking for this issue after simply following the installation instructions : )
Thanks @johangel !

**Comment by pasevin** [comment]
Readme updated

**Comment by esoyke** [comment]
In my case I still had ngx-bootstrap 5.6 instead of 6, missed that in the README. Guess I should have read it. ;)
