### ISSUE TITLE
Facing issues on Angular 7

### ISSUE THREAD

**Issue by leocifer** [webcat12345/ngx-intl-tel-input#212]
I am using Angular 7.2.0 and I am getting the following error.

`WARNING in ./node_modules/ngx-intl-tel-input/fesm5/ngx-intl-tel-input.js 21:64-82
"export 'ɵɵdefineInjectable' was not found in '@angular/core'`

Pasting my package.json file below.

```
{
  "name": "test-site",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@ng-select/ng-select": "^2.19.0",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26",
    "google-libphonenumber": "3.2.2",
    "intl-tel-input": "^14.0.6",
    "jquery": "1.9.1 - 3",
    "ngx-bootstrap": "3.2.0",
    "ngx-intl-tel-input": "^2.2.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.0",
    "@angular/cli": "~7.3.8",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}
```

**Comment by vidhema** [comment]
same issue happens with me

**Comment by BadiuAlexandru** [comment]
Same here
` "ngx-bootstrap": "^5.1.0",
  "ngx-intl-tel-input": "^2.3.1",
  "google-libphonenumber": "^3.2.3",
    "intl-tel-input": "^16.0.2",
`

**Comment by vidhema** [comment]
this is because this repo has no tags of old versions and always fetch latest with angular 8 beta version and gives error in angular 7.

I temporarily resolved it by copying the old node_module folder of this package and place it that contains the angular 7 code of this package.

Hope this helps to others.

**Comment by BadiuAlexandru** [comment]
I downgraded to 

>  "ngx-intl-tel-input": "^2.2.1",
 "intl-tel-input": "^14.0.6",


But the problem now is that I don't have anymore separateDialCode option

**Comment by leocifer** [comment]
> I temporarily resolved it by copying the old node_module folder of this package and place it that contains the angular 7 code of this package.

Can you elaborate on this a little? Or maybe paste the `package.json`

**Comment by leocifer** [comment]
> But the problem now is that I don't have anymore separateDialCode option

I guess this is because separateDialCode was a recent addition

**Comment by BadiuAlexandru** [comment]
Yes, it is a recent addition. Also I have problems with google autofill when try to search for a country, it is impossible to use because of that stupid feature from google and cannot disable it

**Comment by leocifer** [comment]
Might have to find an alternative or create a custom one myself.

**Comment by BadiuAlexandru** [comment]
I like this one, but it really needs to support Angular 7 too, because I need that separateDialCode feature. And about google autofill, I just removed the search option

**Comment by leocifer** [comment]
> I like this one, but it really needs to support Angular 7 too, because I need that separateDialCode feature.

Agreed

**Comment by pasevin** [comment]
Hey, please use this branch for Angular7: https://github.com/webcat12345/ngx-intl-tel-input/tree/angular7

You can build your tarball like this:
```npm run package```

You can find the tarball in ```dist``` folder.

**Comment by RobertJGabriel** [comment]
@pasevin Any update on when this is installable  though npm?

**Comment by fetrarij** [comment]
@pasevin @RobertJGabriel hello, and sorry but I'am creating an npm package for the angular 7 repo, my CI could not follow your manually instruction so I just need to push it to npm.
https://www.npmjs.com/package/ngx-intl-tel-input-angular7

**Comment by AliaksandrBortnik** [comment]
npm uninstall ngx-intl-tel-input --save
npm install  ngx-intl-tel-input@2.2.1 --save

To downgrade to the version that is for Angular 7.

**Comment by pasevin** [comment]
Sorry guys, I can't support different version at the same time, just don't have time and resources for that.

I'm struggling to even keep this one version up to date :)

Today I released v2.3.3 which contains many fixes and feature additions from other people.

Going forward I will only support one version of Angular at the time.


> @pasevin @RobertJGabriel hello, and sorry but I have created an npm package for the angular 7 repo, my CI could not follow your manually instruction so I just need to push it to npm.
> https://www.npmjs.com/package/ngx-intl-tel-input-angular7

@fetrarij if it is useful to you or anyone else, that's great ;)

**Comment by skashfykv** [comment]
> npm uninstall ngx-intl-tel-input --save
> npm install ngx-intl-tel-input@2.2.1 --save
> 
> To downgrade to the version that is for Angular 7.

This worked for me. Thanks

**Comment by evdeepak** [comment]
./node_modules/ngx-intl-tel-input/fesm5/ngx-intl-tel-input.js
22:64-82 "export 'ɵɵdefineInjectable' was not found in '@angular/core'

**Comment by 6matko** [comment]
I am facing the same issue as @evdeepak 
>WARNING in ./node_modules/ngx-intl-tel-input/fesm5/ngx-intl-tel-input.js 22:64-82
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

```
    "ngx-bootstrap": "^5.6.1",
    "@angular/core": "^7.2.0",
    "intl-tel-input": "^14.1.0",
    "ngx-intl-tel-input": "^2.3.4",
```

Any ideas?

**Comment by evdeepak** [comment]
> I am facing the same issue as @evdeepak
> 
> > WARNING in ./node_modules/ngx-intl-tel-input/fesm5/ngx-intl-tel-input.js 22:64-82
> > "export 'ɵɵdefineInjectable' was not found in '@angular/core'
> 
> ```
>     "ngx-bootstrap": "^5.6.1",
>     "@angular/core": "^7.2.0",
>     "intl-tel-input": "^14.1.0",
>     "ngx-intl-tel-input": "^2.3.4",
> ```
> 
> Any ideas?
i don't have ideas
