### ISSUE TITLE
separateDialCode for Angular 7

### ISSUE THREAD

**Issue by pbapan** [webcat12345/ngx-intl-tel-input#213]
is there a way to use separateDialCode  in angular7, I see that your commits has this feature with Angular 7, but it looks like you didnt release a version.

Angular 8 is pretty new version and has major changes and it takes a while to adapt in projects.

is there any other way?

**Comment by pasevin** [comment]
Hey, please use this branch for Angular7: https://github.com/webcat12345/ngx-intl-tel-input/tree/angular7

You can build your tarball like this:
npm run package

You can find the tarball in dist folder.
