### ISSUE TITLE
Scrolling to end of page on search

### ISSUE THREAD

**Issue by leocifer** [webcat12345/ngx-intl-tel-input#214]
Hi there.

Attaching a video link below.

Is there any resolution to this?

[LINK](https://drive.google.com/file/d/1Dhr3IDnrXfk3MFpG_mPEBIknJqZWa_um/view?usp=sharing)

**Comment by pasevin** [comment]
That is a weird one. I don't have time right now, but maybe the author of this feature @snmhinge  can look at this.

**Comment by zaizac** [comment]
Link is expired

**Comment by leocifer** [comment]
@zaizac updated the link

**Comment by rushvora** [comment]
This happens when there are multiple phone inputs on a page, maybe due to both having the same id on the element? (id="phone")

**Comment by forgotten-warrior** [comment]
Any updates?

**Comment by rushvora** [comment]
Fixed it, see [PR#241 ](https://github.com/webcat12345/ngx-intl-tel-input/pull/241)

**Comment by pasevin** [comment]
Update v.2.3.3 has this fixed

**Comment by reynolkb** [comment]
for some reason I'm running into this issue and have version 3.0.5. any tips? it's only happening for mobile

**Comment by rushvora** [comment]
@reynolkb you can directly modify the code in node_modules and play around with the settings to see what works. The changes I made - https://github.com/webcat12345/ngx-intl-tel-input/pull/241/files

The SO answer I referred to - https://stackoverflow.com/questions/11039885/scrollintoview-causing-the-whole-page-to-move/52835382#52835382

Current location in code - https://github.com/webcat12345/ngx-intl-tel-input/blob/96f3132d55867daf9d6599f294bb0061188097ba/projects/ngx-intl-tel-input/src/lib/ngx-intl-tel-input.component.ts#L158
https://github.com/webcat12345/ngx-intl-tel-input/blob/96f3132d55867daf9d6599f294bb0061188097ba/projects/ngx-intl-tel-input/src/lib/ngx-intl-tel-input.component.ts#L203

**Comment by reynolkb** [comment]
@rushvora thanks for the quick reply. can you point me towards where in `node_modules` I can edit the code? I've attached a screenshot of the `ngx-intl-tel-input` folder.

Does your fix mean that if `this.countrySearchText` is false then run the `scrollIntoView` function? The problem I'm facing is each letter the user types into the country code search box moves the entire screen on mobile down to the country you're searching. What I'm trying to do is prevent any movement on the main screen, but allow for the search box to move, just not move the entire view.

**Comment by rushvora** [comment]
@reynolkb the code to edit will be in the esm2015 or the fesm2015 folder. You can experiment and test which one is used.
