### ISSUE TITLE
ngx-intl-tel-input plugin :- Auto fill number field if country is “American samoa” is selected

### ISSUE THREAD

**Issue by puneet0911** [webcat12345/ngx-intl-tel-input#217]
I am using this plugin while testing I found that is you will select the country "American samoa" then type **6845555** then it will fill the input **684-684-5555**.You can also reproduce this issue for "Anguilla" country. 

After autofill, you will not be able to remove it using Backspace button.

Please check here:- https://stackblitz.com/edit/ngx-intl-tel-input-demo

Please let me know the solution for this.

**Comment by larabirabert** [comment]
+1 

And I add that we have this issue for all these country which have +1 as internationnal dialcode 

```
    ['American Samoa', 'as', '1', 1, ['684',]],
    ['Anguilla', 'ai', '1', 1, ['264',]],
    ['Barbados', 'bb', '1', 1, ['246',]],
    ['Bermuda', 'bm', '1', 1, ['441',]],
    ['British Virgin Islands', 'vg', '1', 1, ['284',]],
    ['Cayman Islands', 'ky', '1', 1, ['345',]],
    ['Guam', 'gu', '1', 1, ['671',]],
    ['Saint Vincent and the Grenadines', 'vc', '1', 1, ['784',]],
    ['Trinidad and Tobago', 'tt', '1', 1, ['868',]],
    ['U.S. Virgin Islands', 'vi', '1', 1, ['340',]];
```

Some other as 1 as international dialecode but works fine 

These one OK 
```
    ['Bahamas', 'bs', '1', 1, ['242',]],  
    ['Isle of Man', CountryISO.IsleOfMan, '44', 2, [1624]], 
    ['Jamaica', 'jm', '1', 1, ['876',]],
    ['Montserrat', 'ms', '1', 1, ['664',]], 
    ['Saint Lucia', 'lc', '1', 1, ['758',]], 
    ['Sint Maarten', 'sx', '1', 1, ['721',]], 
    ['Antigua and Barbuda', 'ag', '1', 1, ['268',]], 
```
let me know if you plan to reproduce and correct it ? 
Thanks

**Comment by pasevin** [comment]
This seems like an important issue. If anyone has a solution please submit a PR or at least share your findings here.

**Comment by pasevin** [comment]
I think it's related to ```[separateDialCode]="separateDialCode"]``` because when I remove this, the issue disappears.

**Comment by larabirabert** [comment]
do you think you will be able to push a correction ?

**Comment by larabirabert** [comment]
Thanks I will try it soon

**Comment by pasevin** [comment]
@larabirabert I've just pushed new version 2.3.4 to npm

**Comment by larabirabert** [comment]
1/ we use the version   2.3.1 
but we override the name of the countries in french like this 

`  ngAfterViewInit(): void {
    this.ngxIntlTelInputComponent.allCountries.forEach(pays => pays.name = countryCodeFr[pays.iso2]);
  }`

But with your version 2.3.4 it's not override in french 

How can I migrate to 2.3.4 with my overriding system ? 

2/ in version 2.3.1 and version 2.3.4  without separateDialCode it's work's fine but we would like to use it.
Do you think we can found a fix with separateDialCode  ?
