### ISSUE TITLE
Not supporting emergency helpline numbers like 911

### ISSUE THREAD

**Issue by Gourav102** [webcat12345/ngx-intl-tel-input#218]
Hi, I'm using Angular 7.2.13, with `"ngx-intl-tel-input": "2.1.1"` and `"intl-tel-input": "^14.0.6"`. For common numbers, validation is working properly but for special helpline numbers like 911(US) and 112(IN), it is always giving invalid. How can I allow special numbers like child helpline numbers using this library?

**Comment by pasevin** [comment]
Hm, you have to look into ```google-libphonenumber``` this is the underlying library which we use to validate phone numbers. I'm not sure how they handle international helpline numbers if at all.
