### ISSUE TITLE
How to put the class or set ngclass in angular?

### ISSUE THREAD

**Issue by Arios509** [webcat12345/ngx-intl-tel-input#219]
Hi there, I wish to know if I want to design the length of the form and the layout how suppose I do it? Cause I not sure is my problem is the setting got the problem, since this problem is I put the "form-control", but the layout remains the same.

Even I want to put the ngClass it doesn't help also.

**Comment by pasevin** [comment]
Hi, it looks like this is not a library-related issue. You will be better off asking these kinds of questions on StackOverflow.

All I can add is that you can adjust CSS of the widget, by inspecting the HTML and overriding certain classes. Check out my response here: https://github.com/webcat12345/ngx-intl-tel-input/issues/237

**Comment by pasevin** [comment]
Oh and don't know if you noticed, but we have a property ```[cssClass]``` and ```[id]``` if you want to specify your own custom class or id.

**Comment by Arios509** [comment]
Thanks, let me try about that.
