### ISSUE TITLE
Dependency error: 404

### ISSUE THREAD

**Issue by pedroR** [webcat12345/ngx-intl-tel-input#222]
Hi 
I am trying to use it in an Angular 7 So the steps described here: https://www.npmjs.com/package/ngx-intl-tel-input-angular7. 

I try to run `npm install intl-tel-input-ng7 --save` but it returns a 404 error. Is this correct? 

thanks

**Comment by pasevin** [comment]
```intl-tel-input-ng7``` is not our library. Our library is called ```ngx-intl-tel-input```
We only support Angular versions from 8. I'm not sure how it will behave with Angular7
