### ISSUE TITLE
Unable to see flag images in angular 7 project @2.2.1 version

### ISSUE THREAD

**Issue by abikalwa** [webcat12345/ngx-intl-tel-input#226]
Unable to see the flags both in dropdown as well as the selected flag

It resembles the same as it is in stackblitz demo site. Need help to know how to fix it

**Comment by vinodhkumarcc** [comment]
Same with angular version 8 as well.

**Comment by nupur2710** [comment]
"intl-tel-input": "14.1.0"
  "ngx-intl-tel-input": "2.3.1"

Try to install these specific versions.
It worked for me.

**Comment by vinodhkumarcc** [comment]
> "intl-tel-input": "14.1.0"
> "ngx-intl-tel-input": "2.3.1"
> 
> Try to install these specific versions.
> It worked for me.

> Thanks @nupur2710, this version fixed the above issue.

**Comment by Frz999** [comment]
> "intl-tel-input": "14.1.0"
> "ngx-intl-tel-input": "2.3.1"
> 
> Try to install these specific versions.
> It worked for me.

I tried still not working

**Comment by pasevin** [comment]
Try new clear update of v.2.3.3

**Comment by ShirinShirinak** [comment]
@pasevin v.2.3.3 didn't solve the issue
