### ISSUE TITLE
How to patch value when this used as form control?

### ISSUE THREAD

**Issue by srikanth-menda-97** [webcat12345/ngx-intl-tel-input#231]
Hi, I am on Angular 7 using
"ngx-intl-tel-input": "~2.2.1",
"google-libphonenumber": "^3.2.6",
"intl-tel-input": "^14.0.6".

I am sending phone_number as object to form control
phone_number = {
          countryCode: "IN",
          dialCode: "+91",
          internationalNumber: "+91 88888 88888",
          nationalNumber: "088888 88888",
          number: "8888888888"
        };

I am not able to patch value.

Can anyone help me with some solution?

**Comment by pasevin** [comment]
I'm not sure what you mean by patch value. Is that a library-related issue?

**Comment by MaximRobota** [comment]
the same probl, I wont work with string, but get object into the form control

**Comment by judsonmusic** [comment]
I am working on a solution currently in my project will update once finished. They do not cover anything about saving or parsing the data in their docs. The value attribute also does nothing.

**Comment by pasevin** [comment]
If this is of any help this is how I patch my phone control:

```typescript
this.influencerForm.patchValue({
    phone: unfinishedFormData.phone.internationalNumber,
});
```

**Comment by Amit-Verma01** [comment]
hi, i am currently using angular 17

    "ngx-material-intl-tel-input": "^17.3.0",
i am faceing the same issue, the solution provided above is not working 

 this.studentForm.patchValue({
      localContactNumber: record.localContactNumber? record.localContactNumber: "",
)} 

  this.studentForm = this._formBuilder.group({
    localContactNumber: ['']

Can anyone help me with some solution?

**Comment by srikanth-menda-97** [comment]
Can you share more details of the exact error you are facing

**Comment by Amit-Verma01** [comment]
there is no error showing in console, but when i click on edit button it is not patching but using the same method all other field are patched, and i double checked all field or formcontrolname that names are not wrong.

**Comment by srikanth-menda-97** [comment]
The way you do is right. Can you confirm the value of the variable (
record.localContactNumber )which you are patching

**Comment by Amit-Verma01** [comment]
thank you bro. but error has been fixed
  <ngx-material-intl-tel-input
      [preferredCountries]="['in', 'us', 'nz']"
      [enablePlaceholder]="true"
      [enableSearch]="true"
      cssClass="country-selector"
      (countryChanged)="changeCountry($event)"
      [fieldControl]="phoneControl"
      [initialValue]="phoneNumber"
      [textLabels]="textLabels">
    </ngx-material-intl-tel-input>
    
    setInitialValue(): void {
  const initialPhoneNumber = '';
  this.phoneControl.patchValue(initialPhoneNumber);
}
by using initialvalue

**Comment by srikanth-menda-97** [comment]
Ok thank you
