### ISSUE TITLE
ngx-bootstrap version is causing problem with Angular 8

### ISSUE THREAD

**Issue by isalvadori** [webcat12345/ngx-intl-tel-input#233]
Hi, 
  when compiling the libs for the project I got a lot of error messages in Angular 8, complaining about folders not found and required by `ngx-bootstrap`, from which the project depends on. 
The current `ngx-bootstrap` version used in the project is 3.3.0.
By updating it to version 5.1.1 I was able to properly compile it. 
Could this dependency be updated?

Thank you very much,
Ilenia

**Comment by pasevin** [comment]
Fixed in v.2.3.3
