### ISSUE TITLE
Phone formatter input won't go full width Angular 8

### ISSUE THREAD

**Issue by frankkreutzer** [webcat12345/ngx-intl-tel-input#234]
I have the phone formatter in a a Bootstrap `container-fluid`, `row`, and in that row, 4 columns each `col-md-3`. But the phone formatter input isn't applying a full width in the column - it's shorter than the other inputs (image attached). Is there a fix for this issue?

![image](https://user-images.githubusercontent.com/19320481/70736032-0c685f80-1cd5-11ea-9091-ff2afd6c1f21.png)

**Comment by frankkreutzer** [comment]
I solved this by adding the following CSS to my global styles:
`.intl-tel-input {
  width: 100% !important;
}`

**Comment by gauravmasand09** [comment]
::ng-deep ngx-intl-tel-input .iti{ width: 100% !important; } 
_ This will work as well

**Comment by Cristian3500** [comment]
> ::ng-deep ngx-intl-tel-input .iti{ width: 100% !important; }
> _ This will work as well

@gauravmasand09  thank you for this `::ng-deep ngx-intl-tel-input .iti{ width: 100% !important; }`

**Comment by joker7blue** [comment]
Thank you @gauravmasand09 

`::ng-deep ngx-intl-tel-input .iti{ width: 100% !important; }` work well!

**Comment by Radiatechs-Vaibhavt** [comment]
not working either in local css and global css "  ::ng-deep ngx-intl-tel-input .iti{ width: 100% !important; }   "
