### ISSUE TITLE
Vietnamese phone number format need to be updated.

### ISSUE THREAD

**Issue by forgotten-warrior** [webcat12345/ngx-intl-tel-input#239]
The Vietnamese phone number format changed, so the placeholder in the input field should be updated too.

![image](https://user-images.githubusercontent.com/6366150/71566769-cc82e400-2aec-11ea-8853-78910a86382c.png)

Expected result: placeholder number displayed in xxx xxx xxx format, not xxx xxxx xxx like current.

Thanks.

**Comment by pasevin** [comment]
This is ```google-libphonenumber``` related. We use the latest version they have.
