### ISSUE TITLE
Merge fork for issue #220

### ISSUE THREAD

**Issue by Codem3ay** [webcat12345/ngx-intl-tel-input#240]
Hi,

There's an error during the reset/patch methods on form for the ngx-intl-tel-input forms on angular that was resolved by this [fork](https://github.com/nikos134/ngx-intl-tel-input/commit/03898231852596f8891e2d71d6a74b5a1dcfccaa) by @Niko134. The commit was verified and tested, however it was not merged in the master. Can you please give us a hint if it's going to be for the next milestone? Thx

**Comment by pasevin** [comment]
Hey, this should be fixed in a bit different way now on v.2.3.3. Please check it out.
