### ISSUE TITLE
not able to disable input field using [disabled] ="true"

### ISSUE THREAD

**Issue by sravanReddyajs** [webcat12345/ngx-intl-tel-input#243]
not able to disable input field using [disabled] ="true"

**Comment by Carminati7** [comment]
I found myself having the same issue, they developed the component without the disabled input, but the component has this funcion:
  setDisabledState(isDisabled: boolean): void 
  {
    this.disabled = isDisabled;
  }

You can call it after the afterview cycle, using a viewChild like this:
@ViewChild( NgxIntlTelInputComponent , {static: false }) telInput

  ngAfterViewInit()
  {
    console.log( this.telInput);
    this.telInput.setDisabledState( true )
  }
I coded this morning for my project and did work

**Comment by pasevin** [comment]
Thanks @Carminati7 .

Yes, indeed this is a working way to do it. We need to add it to Readme at some point.

**Comment by pasevin** [comment]
On the other hand, you can disable the input as so:

```typescript
phoneForm = new FormGroup({
   phone: new FormControl({
    value: undefined,
    disabled: true
  }, [Validators.required])
});
```
