### ISSUE TITLE
unable to get validation attribute when using multiple instances of the component in the same page

### ISSUE THREAD

**Issue by Pieter-1337** [webcat12345/ngx-intl-tel-input#246]
When using multiple instances of the <ngx-intl-tel-input> component, it is not possible to perform the phoneValidation, since the following line will never get executed correctly:

var isCheckValidation = document.getElementById('phone').getAttribute('validation');

It will found multiple elements with id 'phone' and won't know which one to take.
Also there should be an extra check here as following to prevent errors from popping op during initialisation: 
const isCheckValidation = document.getElementById('phone') ? document.getElementById('phone').getAttribute('validation') : 'false'; would fix that ...

**Comment by pasevin** [comment]
Hi, the new version on npm v.2.3.3 should address this.
You can now specify your own custom ```[id]``` for each element.
The other issue you are talking about should be fixed as well.
Please try to update and let me know if this is still an issue.
