### ISSUE TITLE
Showing country twice

### ISSUE THREAD

**Issue by mmpatel** [webcat12345/ngx-intl-tel-input#251]
I am trying to use [ngx-intl-tel-input](https://www.npmjs.com/package/ngx-intl-tel-input) , But getting country list twice. Also, flag is not listed in dropdown.
Here is the [stackblitz link](https://stackblitz.com/edit/ngx-intl-tel-input-demo-kypfea) of this screenshot

![stackblitz-ngx-intl-tel-bug](https://user-images.githubusercontent.com/1924980/75890667-b1b64e00-5e54-11ea-9cfe-230c39a230cc.png)

Can anyone help to fix this issue? Or this is a bug in this library?

**Comment by pasevin** [comment]
Fixed in v.2.3.3
