### ISSUE TITLE
Compatablity with angular 9

### ISSUE THREAD

**Issue by joelmuskwe** [webcat12345/ngx-intl-tel-input#256]
ERROR in node_modules/ngx-intl-tel-input/lib/ngx-intl-tel-input.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AuthFeatureShellModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ngx-intl-tel-input) which declares NgxIntlTelInputModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    2 export declare class NgxIntlTelInputModule {

**Comment by joelmuskwe** [comment]
#257

**Comment by Daniyar111** [comment]
When will be supported for Angular 9?

**Comment by pasevin** [comment]
Latest release v.2.4.0 supports Angular 9.
