### ISSUE TITLE
Phone number no longer formatting

### ISSUE THREAD

**Issue by joshuacolvin** [webcat12345/ngx-intl-tel-input#258]
After upgrading to 2.3.4 the phone number is no longer formatted with dashes inside the input. 

**Behavior in 2.3.3**
![ngx-intl-tel-input-demo-2 3 3](https://user-images.githubusercontent.com/8401213/77166178-252da180-6a8a-11ea-9415-5703cb98fa80.png)

**Behavior in 2.3.4**
![ngx-intl-tel-input-demo-2 3 4](https://user-images.githubusercontent.com/8401213/77166222-3bd3f880-6a8a-11ea-8c51-76bd07493bd5.png)

This appears to be related to the fix for this [issue](https://github.com/webcat12345/ngx-intl-tel-input/issues/217).

Thanks!

**Comment by pasevin** [comment]
Yes, it was a part of the bug introduced with "separate dial code" feature.
The phone number was not formatted before that and was not formatted when not using separate dial code.

I will mark this as a feature request.

**Comment by vincentbarat** [comment]
I face the same issue here, and I'm not sure that it is version related: on https://stackblitz.com/edit/ngx-intl-tel-input-demo, you can simply modify any package version in package.json, and the bug occurs, and never disappear even if you go back to original version.

**Comment by pasevin** [comment]
Hey @vincentbarat, I definitely know that this was a part of the bug, because I removed it. The formatting was nice, but it was a byproduct. I just noticed that stackblitz had older version of 'ngx-intl-tel-input' installed and have updated it.

You should see that version prior 2.3.4 was formatting the phone number, and version 2.3.4 got rid of formatting.

**Comment by Laakheey** [comment]
> Yes, it was a part of the bug introduced with "separate dial code" feature. The phone number was not formatted before that and was not formatted when not using separate dial code.
> 
> I will mark this as a feature request.
