### ISSUE TITLE
[DOM] Found 2 elements with non-unique id #phone

### ISSUE THREAD

**Issue by kumarAmaragonda** [webcat12345/ngx-intl-tel-input#259]
When used multiple times there is a element id conflict in dom.

**Comment by pasevin** [comment]
Check ReadMe, you can set your own custom id for each element.

**Comment by kumarAmaragonda** [comment]
Thank you so much for the quick response @Pasevin. But what if it is in for loop and that property is not taking dynamic id as {{i}}.

Thanks and Regards,
Kumar.
