### ISSUE TITLE
ngx-intl-tel-input-angular7 package Update required

### ISSUE THREAD

**Issue by LOMFM** [webcat12345/ngx-intl-tel-input#262]
In this version, the country list in dropdown is duplicated.

You have to reset the allCountries as empty array in the fetchData() function in the ngx-intl-tel-input component.

Could you fix this asap? and update the current npm package update.
Thanks.

**Comment by pasevin** [comment]
Hey, the 'ngx-intl-tel-input-angular7' is a fork by someone else. Refer to them for fixes.
