### ISSUE TITLE
Edit Cursor Issue in the Middle of Number

### ISSUE THREAD

**Issue by LOMFM** [webcat12345/ngx-intl-tel-input#263]
Hi.

I am trying to edit the  phone number using this component.
ex:)
original Number : +1 **469** 489 8983
I am going to this number to +1 **312** 489 8983

So I select the 469 and type the 312.
But after typing "3", the cursor moved to last of the phone number automatically.

Could you upgrade this package with this functionality.
Thanks.

**Comment by pasevin** [comment]
Hey, I think this was an issue which was solved in the recent version 2.3.4. Can you check if you're using the latest version. 

You can try the latest version here as well: https://stackblitz.com/edit/ngx-intl-tel-input-demo
