### ISSUE TITLE
Validation doesn't work when you put an id

### ISSUE THREAD

**Issue by Asiberus** [webcat12345/ngx-intl-tel-input#268]
Hello,

I've found an error in the validation of the phone number. If you put an ID in the `ngx-intl-tel-input` balise, the input is valid as soon as you write one number. 

```
<ngx-intl-tel-input
                  [cssClass]="'form-control'"
                  [preferredCountries]="preferredCountries"
                  [enableAutoCountrySelect]="true"
                  [enablePlaceholder]="true"
                  [searchCountryFlag]="true"
                  [searchCountryField]="[SearchCountryField.Iso2, SearchCountryField.Name]"
                  [selectFirstCountry]="false"
                  [selectedCountryISO]="CountryISO.France"
                  [maxLength]="15"
                  [tooltipField]="TooltipLabel.Name"
                  [phoneValidation]="true"
                  [separateDialCode]="false"
                  id="phoneNumber"
                  formControlName="phoneNumber"
</ngx-intl-tel-input>
```

If you write your ID with brackets `[id]="'phoneNumber'"` the validation work as expected.
```
Version used 
"ngx-intl-tel-input": "2.3.4",
"intl-tel-input": "14.1.0",
"google-libphonenumber": "3.2.8"
```
This bug can be tested in this [stackblitz demo](https://stackblitz.com/edit/ngx-intl-tel-input-demo-spjdbz)

**Comment by zbarinov** [comment]
@Asiberus  When you set id as `id="phoneNumber"` then that id will be set for both a component tag `<ngx-intl-tel-input>` and for the underlying input element. Which will be making impossible to catch a correct element.

**Comment by pasevin** [comment]
I guess @zbarinov means it's not a bug if you use [id] feature.

**Comment by dodomui** [comment]
I'm having the same issue which unable to validate phone number doesn't matter I put id / [id] / [inputId]
