### ISSUE TITLE
flags are not visible in production mode 

### ISSUE THREAD

**Issue by oah7** [webcat12345/ngx-intl-tel-input#274]
I'm using International Telephone Input for Angular, everything is ok in development mode, but in production mode flags are not visible

**Comment by yashlimbachiya97** [comment]
Hey @oah7 , I am not able to see flags even in development mode. Can you help me here?
Attaching the image for your reference.
![image](https://user-images.githubusercontent.com/63908813/82293759-b22da200-99ca-11ea-8ef6-61fe9cdb46ba.png)

**Comment by oah7** [comment]
Hi @yashlimbachiya97 try to follow this example: https://stackblitz.com/edit/intl-input-phone-demo

**Comment by yashlimbachiya97** [comment]
Hi @oah7 . I have followed exactly the same stackblitz example. Can you help me here?

**Comment by oah7** [comment]
I don't have informations about your code so, you can post it in StackOverflow with tags: angular and librephone and ngxintel , and provide more details

**Comment by MVDeveloper1** [comment]
The flags are not visible in the example on stackblitz too.
[ https://stackblitz.com/edit/ngx-intl-tel-input-demo](url)
