### ISSUE TITLE
Countries are listed twice in drop-down

### ISSUE THREAD

**Issue by tbundle** [webcat12345/ngx-intl-tel-input#276]
Same country is displayed twice in drop-down when used "onlyCountries" property.

<ngx-intl-tel-input  [enableAutoCountrySelect]="false"
                  [enablePlaceholder]="false" [onlyCountries]="onlyCountries" [selectFirstCountry]="false"
                  [selectedCountryISO]="CountryISO.India" [maxLength]="15" [phoneValidation]="true"
                  [separateDialCode]="true" name="phone" formControlName="phone"
                  [ngClass]="{ 'is-invalid': submitted && f.phone.errors }">
                </ngx-intl-tel-input>

In component
CountryISO = CountryISO;
  preferredCountries: CountryISO[] = [CountryISO.India];
 onlyCountries = [CountryISO.UnitedArabEmirates, CountryISO.India];

**Comment by tbundle** [comment]
In this case, UAE is displayed twice while India is displayed once.

**Comment by tbundle** [comment]
Anything on this?

**Comment by pasevin** [comment]
Have you tried the latest version? I've used your provided options and no duplicates appear.
