### ISSUE TITLE
country dropdown is not closing when country is selected

### ISSUE THREAD

**Issue by darylvimal** [webcat12345/ngx-intl-tel-input#284]
I have to use bootstrap only for the component where i am using the ngx-intl-input, so i removed the bootstrap.min.css from angular.json but imported in specific component. In this case, when i select the country from dropdown,the dropdown is not closing automatically but it working fine when i use the bootstrap.min.css in angular.json.
The problem i should not use bootstrap.min.css in angular.json because it will override all my component and giving the misaligned css overall my project.

For more info, please check the link below
https://stackoverflow.com/questions/62221038/ngx-intl-tel-input-node-module-changing-the-styles

**Comment by pasevin** [comment]
As you correctly pointed out this lib is dependant on ```ngx-bootstrap```.
Until we do, you have to figure out by yourself how to achieve what you want in your particular case. This is not a library issue.
