### ISSUE TITLE
enhancements

### ISSUE THREAD

**Issue by diogoflowinn** [webcat12345/ngx-intl-tel-input#288]
hello to all. 
thank you for this library.

The id issue got solved (thank you), but in my code i have a form group, and the labels use the "for" attribute, wich are standard and expect and id (not inputId) and give a "Invalid Id Reference".
It builds  but doesn't bind.

Another enhancement is, when you type the country's name, the country should appear on the top and not at the bottom of the list. (If you write Brazil for example, it shows at the bottom)

Thanks

My bit of code:
  
<label class="form-control-label" for="field_phone" jhiTranslate="app.contact.phone" >Phone</label>
                <div class="input-group input-group-sm">
                    <ngx-intl-tel-input
                        [inputId]="'field_phone'"
                        ......

**Comment by pasevin** [comment]
I think you don't fully understand how to use this library, or I am misunderstanding you. There is no issues with ``for=`` labels as I'm using it constantly. 

```[inputId]``` will be passed and set to the child ```<input id=``` element of the ```<ngx-intl-tel-input>```. You can additionally set standard HTML ```id``` on each ```ngx-intl-tel-input``` if you want.

Which Ids you set or don't is all up to you. Can you share a properly formatted code of your project so I can determine if it's a library issue or not?

This is roughly how it should be used (label included):

```typescript
<form [formGroup]="myForm"
	#f="ngForm"
	(ngSubmit)="onSubmitMyForm($event)">
<label for="{{controlName}}"
	class="input-label">{{text}}</label>
<ngx-intl-tel-input [cssClass]="'input-text w-input'"
	[inputId]="controlName"
	[searchCountryFlag]="true"
	[preferredCountries]="[CountryISO.UnitedStates, CountryISO.UnitedKingdom]"
	[enablePlaceholder]="true"
	[enableAutoCountrySelect]="true"
	formControlName="{{controlName}}"></ngx-intl-tel-input>
</form>
```

**Comment by diogoflowinn** [comment]
Hello sorry for the late reply, i was out of the office.

(a nice enhancement is to show the country you are searching for, when you
type, ate the beginning of the list and not at the bottom.)

in attachment are the my samples.

if you copy paste to  https://stackblitz.com/  IT WORKS, on my project, it
does not.
I've installed the new version "ngx-intl-tel-input": "^2.4.1", and if i
debug your code at:


const phoneNumberValidator = (control) => {
    if (!control.value) {
        return;
    }
    // Find <input> inside injected nativeElement and get its "id".
    const el = control.nativeElement;
    const inputBox = el.querySelector('input[type="tel"]');
    if (inputBox) {
        const id = inputBox.id;
..........

the *const el* is undefined therefore validation dos not work on my side.

ERROR TypeError: Cannot read property 'querySelector' of undefined
    at phoneNumberValidator (ngx-intl-tel-input.js?b77e:1741)

thank you.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pasevin** [comment]
Most likely this is why: https://github.com/webcat12345/ngx-intl-tel-input/issues/289

**Comment by diogoflowinn** [comment]
if you look at the the code i sent you, you see its very simple, and no
ngModel is used.

like i said, validation works on  stackblitz but not on my server, so it
must be something else on my side...

  thank you for the reply.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by diogoflowinn** [comment]
its working, after some compilation issues.

(can you tell how to expand the country-list upwards?)
thank you

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Diogo Eira <diogo.eira@flowinn.biz> escreveu no dia terça, 16/06/2020 à(s)
15:26:

>
> if you look at the the code i sent you, you see its very simple, and no
> ngModel is used.
>
> like i said, validation works on  stackblitz but not on my server, so it
> must be something else on my side...
>
>   thank you for the reply.
>
>
> <http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Virus-free.
> www.avg.com
> <http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
> <#m_1812769965648719814_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>


-- 

Cumprimentos,

Diogo Eira

Fullstack Developer
Telefone: ​212 483 800 <+351%E2%80%8B212483800>
Telemóvel: 926 728 741 <+351926728741>
[image: Logo] <https://www.flowinn.biz/>
[image: Facebook icon]  <https://www.facebook.com/grupoflowinn>[image:
LinkedIn icon] <https://www.linkedin.com/company/flowinn/>
www.flowinn.biz

AVISO LEGAL A informação presente nesta mensagem, bem como em qualquer dos
seus anexos é confidencial e destinada exclusivamente ao(s)
destinatário(s). Qualquer utilização desta informação que não esteja de
acordo com o seu objectivo, qualquer disseminação ou divulgação, total ou
parcial, é proibida excepto se formalmente aprovada. A Internet não garante
a integridade desta mensagem, a qual poderá ter sido interceptada,
corrompida, perdida, atrasada ou acrescida de vírus. Assim, a Flowinn não
se responsabiliza pela mensagem se modificada.

**Comment by pasevin** [comment]
No way to expand it outside the library. Only with the new release. If you want you can submit a PR. Closing this issue now.
