### ISSUE TITLE
ERROR TypeError: Cannot read property 'querySelector' of undefined

### ISSUE THREAD

**Issue by alitarfa** [webcat12345/ngx-intl-tel-input#291]
Hello, 
when I type using the Input field this error appears for me 
main-es2015.e7a4deffaa941d5aea15.js:1 ERROR TypeError: Cannot read property 'querySelector' of undefined
    at CS (main-es2015.e7a4deffaa941d5aea15.js:1)
    at main-es2015.e7a4deffaa941d5aea15.js:1
    at Array.map (<anonymous>)
    at main-es2015.e7a4deffaa941d5aea15.js:1
    at main-es2015.e7a4deffaa941d5aea15.js:1
    at main-es2015.e7a4deffaa941d5aea15.js:1
    at Array.map (<anonymous>)
    at main-es2015.e7a4deffaa941d5aea15.js:1
    at Lm.validator (main-es2015.e7a4deffaa941d5aea15.js:1)
    at Lm._runValidator (main-es2015.e7a4deffaa941d5aea15.js:1)

Anyone can help, please

**Comment by pasevin** [comment]
Have you looked at this: https://github.com/webcat12345/ngx-intl-tel-input/issues/289 ?
Maybe you're using it incorrectly.

**Comment by pasevin** [comment]
Hey the 'querySelector' issue was indeed occurring , can you check if the new 2.4.2 version has fixed it?
