### ISSUE TITLE
Mistake enableAutoCountrySelect

### ISSUE THREAD

**Issue by dvkudashev** [webcat12345/ngx-intl-tel-input#295]
![image](https://user-images.githubusercontent.com/42639988/85131185-fd8fd600-b23e-11ea-8b57-88331360667d.png)

![image](https://user-images.githubusercontent.com/42639988/85131197-02ed2080-b23f-11ea-9f3a-1b303cb0630a.png)

![image](https://user-images.githubusercontent.com/42639988/85131138-ebae3300-b23e-11ea-8d06-d2e0a3685eb1.png)

Nessesary to use: 

```
value = (value) ? value.toString().replace(/[-\s]/g, '').trim() : '';
if (value.length > 3) {
        const phoneUtil = lpn.PhoneNumberUtil.getInstance();
        const number = phoneUtil.parseAndKeepRawInput(value);
        const code = phoneUtil.getRegionCodeForNumber(number);
}
```

**Comment by pasevin** [comment]
Fixed by https://github.com/webcat12345/ngx-intl-tel-input/pull/321
