### ISSUE TITLE
Enable disable option

### ISSUE THREAD

**Issue by rkarthik6** [webcat12345/ngx-intl-tel-input#296]
Please provide option to make input readonly and disable.

**Comment by rushvora** [comment]
What's stopping you from doing so now?

Here's a working stackBlitz where I disable/enable the form.

https://stackblitz.com/edit/ngx-intl-tel-input-demo-gz52yf

**Comment by rkarthik6** [comment]
Please provide the option to make input read-only.

**Comment by sudarshansb143** [comment]
@rushvora  The stackBlitz link throws not found.
![image](https://github.com/webcat12345/ngx-intl-tel-input/assets/43947282/87220760-fc8a-4bd4-a4f9-afbd2c4178b7)
