### ISSUE TITLE
Component doesn't handle ChangeData object as input to control.setValue

### ISSUE THREAD

**Issue by kinoroy** [webcat12345/ngx-intl-tel-input#299]
A common use case is to store your form values in a store with NgRx/NGXS/etc and persist them so you can replenish the form values after coming back to the page. The ngx-intl-tel-input component sets the formControl's value to be a `ChangeData` object like this one:
```
{
    "number": "778-555-1234",
    "internationalNumber": "+1 778-555-1234",
    "nationalNumber": "(778) 555-1234",
    "e164Number": "+17785551234",
    "countryCode": "CA",
    "dialCode": "+1"
 }
```
However, if one stores this form state and later attempts to replenish the values with this object, then the input field will display the text value `[object Object]` instead of the phone number, because the component assumes the input value to be a string.

The component should detect the case where the setValue input is an object, so that its state may be automatically replenished from a store.

**Comment by k04Akhil** [comment]
@kinoroy Can you please explain in detail. i couldnt find any docs for this
