### ISSUE TITLE
Phone field was invalid after using setValue method.

### ISSUE THREAD

**Issue by AsakaRin** [webcat12345/ngx-intl-tel-input#305]
I have a phone number valid. When I use setValue to set that phone, it takes me invalid. But when I let the input field is empty or I change something with this input and retype that phone number, it takes me valid.

Example: 
Step 1: value initial: '' - valid
Step 2: value after setValue: '0374306505' - invalid
Step 3: value after changing something with input field: '0374' - invalid
Step 4: value after retype number: '0374306505' - valid

**Comment by pasevin** [comment]
Please verify if the same issue appears with the latest version.
