### ISSUE TITLE
Transparent Dropdown Issue

### ISSUE THREAD

**Issue by Dave-Nandwa** [webcat12345/ngx-intl-tel-input#308]
Hi, 

Does anyone get this issue? The Countries Dropdown is transparent and it appears behind other elements here are my versions.

```
"ngx-intl-tel-input": "^2.4.3",
"intl-tel-input": "^14.1.0",
 "google-libphonenumber": "^3.2.7",
```

**Comment by pasevin** [comment]
Not related to this library. You can see the demo on stackblitz.
