### ISSUE TITLE
control in overflow:auto container

### ISSUE THREAD

**Issue by darkovuj** [webcat12345/ngx-intl-tel-input#310]
If we place this control in parent div with overflow:auto and specific height it will not render dropdown over parent div. How to do that?

demo

https://stackblitz.com/edit/angular-ngx-intl-tel-input-rydwuc

**Comment by pasevin** [comment]
This question is not related to the library.

**Comment by tahirjamil92** [comment]
any solution on this?

**Comment by tahirjamil92** [comment]
![image](https://user-images.githubusercontent.com/96121891/170046949-75811742-c9d5-40ce-b18c-5ec0572040e5.png)
the above image I shared shows that our dropdown ul html tag comes under your container so we need a call which should append our ul to body or and div which we need
