### ISSUE TITLE
cant bind countrycode and number in ngx-intl-tel at once got this error Expression has changed after it was checked. Previous value: '123123'. Current value: 'undefined'.

### ISSUE THREAD

**Issue by muhammadahmadkhan2024** [webcat12345/ngx-intl-tel-input#312]

**Comment by pasevin** [comment]
An example or stackblitz would be helpful :)

**Comment by william-levi** [comment]
+1 experiencing this too

**Comment by william-levi** [comment]
@muhammadahmadkhan2024  i solve the problem by using setTimeout;
//api call here
setTimeout(() => {
                this.countryCode = result.mobile.countryCode.toLowerCase();
})
