### ISSUE TITLE
Would it be possible to remove the dependency on bootstrap by importing just the needed css?

### ISSUE THREAD

**Issue by GaretWebster** [webcat12345/ngx-intl-tel-input#333]
I would love to use ngx-intel-tel-input, but I absolutely don't want the 10,000 lines of css that come with bootstrap. In addition to my app never using 90% of the css, a lot of the remaining 10% conflicts with the way I want the app to be.

Is it possible to include only the necessary css from bootstrap directly in the intlTelInput.css?

I am still trying to figure out exactly what css is used from bootstrap, but it seems most of it revolves around the .dropdown-menu class.

**Comment by pasevin** [comment]
That would be awesome, if someone could create a propper PR for this, I would make sure to merge it ASAP :)
