### ISSUE TITLE
Interfaces folder is missing from the package

### ISSUE THREAD

**Issue by omitewary** [webcat12345/ngx-intl-tel-input#335]
Importing **_NgxIntlTelInputModule_**  in the module throws below error:
```
`ERROR in node_modules/ngx-intl-tel-input/lib/ngx-intl-tel-input.component.d.ts:6:33 - error TS2307: Cannot find module './interfaces/change-data' or its corresponding type declarations.

6 import type { ChangeData } from './interfaces/change-data';`
```
Please find below package.json file

```
{
  "name": "container-verification",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.2",
    "@angular/cdk": "^10.0.1",
    "@angular/common": "~10.0.2",
    "@angular/compiler": "~10.0.2",
    "@angular/core": "~10.0.2",
    "@angular/forms": "~10.0.2",
    "@angular/material": "^10.0.1",
    "@angular/material-moment-adapter": "^10.0.1",
    "@angular/platform-browser": "~10.0.2",
    "@angular/platform-browser-dynamic": "~10.0.2",
    "@angular/router": "~10.0.2",
    "@ngx-translate/core": "^12.1.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "bootstrap": "^4.4.1",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-prettier": "^3.1.2",
    "google-libphonenumber": "^3.2.13",
    "intl-tel-input": "^17.0.3",
    "lodash.debounce": "^4.0.8",
    "moment": "^2.27.0",
    "ngx-bootstrap": "^6.1.0",
    "ngx-intl-tel-input": "^3.0.2",
    "rxjs": "~6.5.4",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.1",
    "@angular/cli": "~10.0.1",
    "@angular/compiler-cli": "~10.0.2",
    "@angular/language-service": "~10.0.2",
    "@compodoc/compodoc": "^1.1.11",
    "@types/jest": "^24.0.15",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "^2.19.2",
    "@typescript-eslint/parser": "^2.19.2",
    "codelyzer": "^5.1.2",
    "eslint": "^6.8.0",
    "eslint-plugin-typescript": "^0.14.0",
    "husky": "^4.2.2",
    "jest": "^24.8.0",
    "jest-preset-angular": "^8.0.0",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.6"
  }
}

```

**Comment by vasco88** [comment]
It happens me the same

**Comment by vasco88** [comment]
But to bypass this issue, as a hot fix, you can add it manually: https://github.com/webcat12345/ngx-intl-tel-input/blob/master/projects/ngx-intl-tel-input/src/lib/interfaces/change-data.d.ts

It worked for me.

Obviously, very time you do a npm i, you must add this file manually.

Regards,

**Comment by omitewary** [comment]
@vasco88  yes that's fine if it runs locally but not feasible when the app needs to be deployed in some environment. In that case, change might be done in the build script but that's kind of a workaround

**Comment by crutchcorn** [comment]
Could the issue be because the interface is not exported from the `public-api.ts` file?

https://github.com/webcat12345/ngx-intl-tel-input/blob/master/projects/ngx-intl-tel-input/src/public_api.ts

**Comment by crutchcorn** [comment]
Downgrading to `3.0.1` also fixes the problem. Seems like it was a regression introduced into `3.0.2`

**Comment by tiagomartins91** [comment]
Same here into 3.0.2 version

**Comment by pasevin** [comment]
Hey, as mentioned in the https://github.com/webcat12345/ngx-intl-tel-input/commit/52041c736b5ff6b6e9853322fcb888d83fd71845#r42720417 is the cause...

I was not aware that people are accessing ```ChangeData``` interface from outside the library as it was never documented in the ReadMe.

What is the reason for doing that? 
Might need to expose it again as it was previously...

**Comment by pasevin** [comment]
> Could the issue be because the interface is not exported from the `public-api.ts` file?
> 
> https://github.com/webcat12345/ngx-intl-tel-input/blob/master/projects/ngx-intl-tel-input/src/public_api.ts

I don't remember it being a part of the public API. I never declared or used this interface outside the library.
Looks like when packaging for Angular10 this file is being ignored by the packager by default.
But when compiling for older Angular versions, the file stays.

I can see that a few people are using ```ChangeData``` interface, so will try to include it into public_api.d.ts
