### ISSUE TITLE
Logging an unknown phone number 

### ISSUE THREAD

**Issue by yase11** [webcat12345/ngx-intl-tel-input#346]
![image](https://user-images.githubusercontent.com/46924226/101359303-08b2ed00-38d7-11eb-8b27-f4b3e311591b.png)

Just reminding to remove the console.log(phoneNumber) in line 2079 in library. Don't know if there more to debug aside from this... I'm using v.3.0.4.

**Comment by pasevin** [comment]
Thanks again, I've published the fix on npm.
