### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by shreyaasridhar** [webcat12345/ngx-intl-tel-input#354]
Hi guys!
We want to use your library in our project but unfortunately, we are on Angular 11. Are you guys working on releasing support for Angular 11?

**Comment by pasevin** [comment]
Hey glad to hear! I'm the only active maintainer, and will try to look into it in the near future :)
I'm pretty active with accepting PRs and publishing on npm. So if you want you can take it upon yourself and submit a PR. 
I will take care of the rest.

**Comment by crutchcorn** [comment]
We're currently using this dependency with our Angular 11 app without any issues. I think it's as simple as updating your peer dep semver range. Opening a PR now
