### ISSUE TITLE
Angular 9 compile error

### ISSUE THREAD

**Issue by rjosephe2open** [webcat12345/ngx-intl-tel-input#357]
Hi! Does any one have the following issue while compiling an angular 9 app using this package?: ERROR in node_modules/ngx-intl-tel-input/lib/ngx-intl-tel-input.component.d.ts:6:13 - error TS1005: '=' expected.
6 import type import * as ɵngcc0 from '@angular/core';

**Comment by pasevin** [comment]
There's a demo link with Angular 9 in the readme doc. There should be no compiling issues. You could get a better answer in StackOverflow probably.

**Comment by dodopok** [comment]
I'm having the same problem here.

**Comment by FractalMind** [comment]
Use version 2.6

package.json:
"ngx-intl-tel-input": "2.6.0",
