### ISSUE TITLE
Flags are not visible 

### ISSUE THREAD

**Issue by ShirinShirinak** [webcat12345/ngx-intl-tel-input#362]
I just started using this library and the flags are not visible! It seems the pictures are not loading or something. I had a look at the Demos and they're the same! The pictures are missing. 

This is from the demo here actually, I think it's the same issue:
![image](https://user-images.githubusercontent.com/14070709/110232808-27775d00-7f74-11eb-81d2-87ee66502406.png)

Can someone help please! Thank you

**Comment by ShirinShirinak** [comment]
I found out I had few lines in my main css file that was interfering. closing the issue now.

**Comment by asongkai** [comment]
How you slove?

**Comment by ShirinShirinak** [comment]
> How you slove?

Oh it's been a while, I don't remember well. I think there were styling for the flag in my main css file, I think the library added them there when I installed it.  

I commented out .iti__flag {...} and @media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
   .iti__flag {...} and .iti {...} and then the problem was gone.
