### ISSUE TITLE
Impossible to set width of form control

### ISSUE THREAD

**Issue by iFederx** [webcat12345/ngx-intl-tel-input#380]
Hi,
is there a way to set the width of the form control?
I tried passing a class to `cssClass` with `width: 100%`, but it doesn't work. Any suggestion? :)
Thanks

**Comment by iFederx** [comment]
Solved

**Comment by Scantraxx123** [comment]
@iFederx Could you explain you did it, please?

**Comment by jorool** [comment]
> Solved

How did you solve it?

**Comment by guybedo** [comment]
Easier to just add an id to the component: 

<ngx-intl-tel-input id="mobileNumber">

 and then add in your css something like:

#mobileNumber .iti {
	width: 100%;
}
