### ISSUE TITLE
Angular 12 Upgrade

### ISSUE THREAD

**Issue by Tea-Ice** [webcat12345/ngx-intl-tel-input#383]
Angular 12 gives peer dependency issues, please fix

**Comment by abdallahmaali** [comment]
I  installed the package with angular 12  but it's not working or triggered at all without any errors in the console or terminal @Tea-Ice did you have same probelm?

**Comment by duxor** [comment]
@Tea-Ice @abdallahmaali Works for me in v12, but I am using lib version `15.1.2` because I don't have bootstrap installed in the project.

**Comment by khlewesamer** [comment]
dose this issue solved ?, i have angular 12 but ngx-intl-tel not work at all, pls could u upgrade it

**Comment by Tea-Ice** [comment]
I got it working, but it required me to exclude it from ngcc. It is on another machine, so will give you guys the snippet on Tuesday.

**Comment by anass-lahlal** [comment]
It works, but we need official support for Angular 12 to get rid of the warnings

**Comment by Rajnish4444** [comment]
@Tea-Ice @anass-lahlal  can you please provide the steps to the workarounds you used, I am unable to get it to work with angular 12

**Comment by pasevin** [comment]
More information would be needed. I have my project to Angular 12 and it works without issues.

**Comment by duxor** [comment]
#404

**Comment by pasevin** [comment]
Update has been pushed to npm. Working example: https://stackblitz.com/edit/ngx-intl-tel-input-demo-ng-12
