### ISSUE TITLE
search is not working

### ISSUE THREAD

**Issue by sumaiya-ahmkh** [webcat12345/ngx-intl-tel-input#398]
using angular9

other versions are:
"google-libphonenumber": "^3.2.22",
"intl-tel-input": "^17.0.3",
"ngx-intl-tel-input": "^3.1.1",
"ngx-bootstrap": "^6.2.0"

followed codes written in stackblitz demo

**Comment by pasevin** [comment]
If it's working on stackblitz examples, it should work for you too. Unless your environment is set up improperly.
