### ISSUE TITLE
Angular 13 issue.

### ISSUE THREAD

**Issue by parksmart-dev** [webcat12345/ngx-intl-tel-input#410]
Found: @angular/common@13.0.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"8.x - 12.x" from ngx-intl-tel-input@3.1.3
npm ERR! node_modules/ngx-intl-tel-input
npm ERR!   ngx-intl-tel-input@"^3.1.1" from the root project

**Comment by NayeBeckham** [comment]
Hello, I would like to contribute. Can I create a PR to solve the issue? Thank you!

**Comment by webcat12345** [comment]
Of course yes! Always welcome.

**Comment by NayeBeckham** [comment]
Hello, the PR is ready to review!

**Comment by phyr0s** [comment]
@NayeBeckham  i review your pr and you need to make few changes in order to works fine with angular 13
