### ISSUE TITLE
Provide phone number validation demo

### ISSUE THREAD

**Issue by Chathur** [webcat12345/ngx-intl-tel-input#42]
It will be great if you could provide a demo for the phone number validation. 
So far Ive added the component and my code looks as follows.

` <ngx-intl-tel-input [(value)]="company.contactInfo[0].phone"></ngx-intl-tel-input>`

If you could provide me further more details for validate number it will be great.

**Comment by boogie4eva** [comment]
I used the component as well but couldnt  find any way to validate input

**Comment by lailaEla** [comment]
`const phoneUtil = _.PhoneNumberUtil.getInstance();
let isValidNumber = phoneUtil.isValidNumberForRegion(phoneNumber, countryCode);
console.log(isValidNumber); // true or false`

**Comment by pasevin** [comment]
https://stackblitz.com/edit/ngx-intl-tel-input-demo https://stackblitz.com/edit/ngx-intl-tel-input-demo

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
