### ISSUE TITLE
Adding Material styles

### ISSUE THREAD

**Issue by ududsha** [webcat12345/ngx-intl-tel-input#80]
Cant we add material style support for this valuable package?

**Comment by pasevin** [comment]
Pull requests are welcome :]

**Comment by junaidahmed501** [comment]
There is this package called [` ngx-mat-intl-tel-input`](https://github.com/tanansatpal/ngx-mat-intl-tel-input) that is actually forked from this same package & it has Angular Material support.
I think the only thing that the ` ngx-mat-intl-tel-input` package is doing is to add a `matInput `directive on the HTML input element.
